project:
  type: book
book:
  title: Introduction to Human Biology Laboratory Workbook
  author:
  - name: George Mateja
    affiliations:
      - The Community College of Baltimore County
  version: 4
  date: "2024"
  chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    - 03.qmd
    - 04.qmd
    - 05.qmd
    - 06.qmd
    - 07.qmd
    - 08.qmd
    - 09.qmd
    - 10.qmd
    - 11.qmd
    - 12.qmd
    - 13.qmd
    - 14.qmd
    - 15.qmd
    - 16.qmd
    - 17.qmd
    - 18.qmd
    - 19.qmd
    - 20.qmd
    - 21.qmd
    - 22.qmd
    - 23.qmd
    - att.qmd
format:
  html:
    theme:
      - cosmo
      - brand